exclude: 'provision/ansible/prod/roles/contrib|provision/ansible/dev/roles/contrib|vendor|docs|.serverless|.serveless_nextjs|node_modules|migrations|.git|.tox|.gen'
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3.8.0

repos:
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.11.1
    hooks:
      - id: validate_manifest
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.1
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
      - id: python-bandit-vulnerability-check
        args: []
        files: .py$
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.7.2
    hooks:
      - id: pylint
        exclude: __pycache__|migrations|conf.py|_build|.tox|pootle/static|pootle/translations|pootle/locale|pootle/assets|templates
        args:
          - --rcfile=.github/linters/.pylintrc
          - --disable=no-name-in-module,import-error,ungrouped-imports
          - --ignore=settings_test, migrations
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
        exclude: migrations|conf.py|_build|.tox|pootle/static|pootle/translations|pootle/locale|pootle/assets|templates
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: detect-private-key
        files: ^(?!\.?git-crypt)
      - id: check-merge-conflict
      - id: trailing-whitespace
        files: ^tf|-|\.(py|tfvars|tf|tfenv|env|yml|yaml|pem|key|mock)$
      - id: end-of-file-fixer
        files: ^tf|-|\.(py|env|yml|yaml|pem|key|mock)$
      - id: check-added-large-files
        files: ^tf|-|\.(py|env|yml|yaml)$
      - id: check-case-conflict
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-byte-order-marker
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: check-symlinks
      - id: name-tests-test
        args:
          - --django
      - id: file-contents-sorter
      - id: fix-encoding-pragma
      - id: sort-simple-yaml
      - id: mixed-line-ending
        fix: lr
      - id: check-executables-have-shebangs
  - repo: https://github.com/tcassou/python-pre-commit-hooks
    rev: 3383e2f83463370cf4651040fb697a636bb0374e
    hooks:
      - id: do_not_commit
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
      - id: shellcheck
        exclude: (^provision/script/wait-for-it.sh$|^provision/git/hooks/prepare-commit-msg$)
        args:
          - --exclude=SC1072,SC1073,SC2068
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.0
    hooks:
      - id: docker-compose-check
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: system
        entry: ./node_modules/prettier/bin-prettier.js
        args:
          - '--write=true'
          - '--list-different'
          - '--config=.github/linters/prettier.config.js'
          - '--ignore-path=.github/linters/.prettierignore'
        files: \.(js|jsx|json|ts|tsx|mjs|d.ts|md|yml|yaml|gql|graphql|mjml)$
        exclude: node_modules
      - id: eslint
        name: eslint
        language: system
        pass_filenames: true
        entry: node_modules/eslint/bin/eslint.js --config=.github/linters/.eslintrc.js --ignore-path=.github/linters/.eslintignore --color
        args:
          - '--fix'
        files: \.(js|jsx|ts|tsx|mjs|d.ts)$
      - id: stylint
        name: stylint
        language: system
        pass_filenames: true
        entry: node_modules/stylelint/bin/stylelint.js --config=.github/linters/.stylintrc --syntax less **/*.less
        args: [--fix]
        files: \.(css|scss|sass|less)$
      - id: dockerfile-provides-entrypoint
        name: hadolint
        description: Lint Dockerfiles with hadolint
        language: docker_image
        entry: --entrypoint /bin/hadolint hadolint/hadolint:latest --ignore DL3008 --ignore DL3013 --ignore DL3018 --ignore DL3008 --ignore DL4006 --ignore SC2001 --ignore SC2086 --ignore SC2102 -
        types: [file]
        files: Dockerfile(.*)
