default_stages:
  - commit

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args: [--ignore-words=.codespell-ignores]
        exclude: >
          (?x)^(
            .+\.vendor\/.*$|
            .+\.node_modules\/.*$|
            .+\.lock$|
          )$
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v5.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@hadenlabs/commitlint-config']
        args:
          - --config=.github/linters/.commitlintrc.json
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: detect-private-key
        files: ^(?!\.?git-crypt)
        exclude: >
          (?x)^(
            .+\.gitleaks.toml$|
          )$
      - id: check-merge-conflict
      - id: check-added-large-files
        files: ^tf|-|\.(py|env|yml|yaml)$
      - id: check-case-conflict
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-byte-order-marker
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: check-symlinks
      - id: file-contents-sorter
      - id: fix-encoding-pragma
      - id: sort-simple-yaml
  - repo: https://github.com/hadenlabs/pre-commit-hooks
    rev: 29c3f47f8fa0ec66d35ccbad761b7cf299e5ee19
    hooks:
      - id: do-not-commit
      - id: markdown-link-check
        args:
          - --config=.github/linters/markdown-link-config.json
        exclude: \.tpl.md$
      - id: shellcheck
        exclude: >
          (?x)^(
            .+\.provision/git/hooks/prepare-commit-msg$|
            .+\.tpl.sh$|
          )$
        args:
          - --exclude=SC1072,SC1073,SC2068
      - id: todocheck
      - id: gitleaks
        args:
          - --path=.
          - --repo-config-path=.github/linters/.gitleaks.toml
          - --verbose
      - id: prepare-commit-msg
        stages: [prepare-commit-msg]
