style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/luismayta/dotfiles
options:
  commits:
    filters:
      Type:
        - chore
        - feat
        - fix
        - perf
        - refactor
    sort_by: Scope

  commit_groups:
    group_by: Type
    sort_by: Title
    title_order:
      - feat
      - chore
      - fix
      - perf
      - refactor

    title_maps:
      feat: âœ¨ Features
      fix: ğŸ› Bug Fixes
      fixed: ğŸ› Bug Fixes
      perf: âš¡ Performance Improvements
      docs: ğŸ“ Docs changes
      refactor: ğŸ¨ Code Refactoring
      rename: ğŸšš Renamed
      revert: âª Reverted
      update: ğŸ”„ Updates
      build: ğŸ‘· Building scripts changes
      chore: Other changes
      style: ğŸ’„ Code styling
      ci: ğŸ‘· CI changes

  header:
    pattern: "^(\\w+)(?:\\s*.*)?(?:\\s*\\((.*?)\\))?:\\s*(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject

  merges:
    pattern: "^Merge branch '(\\w+)'$"
    pattern_maps:
      - Source

  reverts:
    pattern: "^Revert \"([\\s\\S]*)\"$"
    pattern_maps:
      - Header

  notes:
    keywords:
      - BREAKING CHANGE
      - ğŸ’¥
