name: sonarqube

on:
  push:
    branches:
      - main

    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      # https://semver.org/ proper release tags, more or less
      - "v[0-9]+.[0-9]+.[0-9]+"
      # prerelease tags, more or less
      - "v[0-9]+.[0-9]+.[0-9]+-*"

env:
  SONAR_HOST_URL: "${{ secrets.SONAR_HOST_URL }}"
  SONAR_LOGIN: "${{ secrets.SONAR_LOGIN }}"

jobs:
  sonar-scan:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out a copy of the repo
        if: ${{ !env.ACT }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Scan Sonar
        if: ${{ !env.ACT }}
        run: task sonar:scan
